#!/usr/bin/env ruby

require 'bundler/setup'
require 'my_last_cv'

if ARGV.length < 2
  puts "Usage: my_last_cv input.md output.pdf"
  exit 1
end

input, output = ARGV

pro = MyLastCV::Style.new(
  header_font:  "Inter",
  header_size:  22,
  section_font: "Inter",
  section_size: 12,
  body_font:    "Lora",
  body_size:    10,
  page_options: { margin: 36 },
  accent_color: "1F7AE0" # blue
)

MyLastCV.generate(input, output, style: pro)

puts "CV généré : #{output}"
